// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgttxbybqehjlljwruzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndHR4YnlicWVoamxsandydXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTE2NzcsImV4cCI6MjA2ODA2NzY3N30.uHi45-Vxl4GsMXOnBVtWTpFwDMiwG8jR5t3SANxEbAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});